### ISSUE TITLE
Unable to install @cycle/core

### ISSUE THREAD

**Issue by mingfang** [mixu/npm_lazy#55] opened 2015-11-22 15:29 UTC
npm i @cycle/core
npm ERR! fetch failed http://localhost:9999/@cycle/core/-/core-5.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

It install fine without npm_lazy

**Comment by CL0SeY** [comment] 2015-12-12 01:21
Duplicate of #52

**Closed by CL0SeY** 2015-12-12 01:21 UTC
