### ISSUE TITLE
Not all packages are getting cached

### ISSUE THREAD

**Issue by tonyjchong** [mixu/npm_lazy#44] opened 2014-10-22 18:23 UTC
I think I'm missing something but none of my packages that are listed in the dependencies section of my package.json are getting cached, but modules in my devDependencies are, along with some other modules I do not have listed. I'm guessing the latter is because those modules have dependencies of their own.

Thanks.

**Comment by fantapop** [comment] 2015-04-14 20:53
Was there ever a resolution for this?

**Comment by CL0SeY** [comment] 2015-04-14 23:51
I'm happy to investigate if I get an example package.json file so we can look at reproducing the issue. I suspect it's specific to some particular urls being loaded that are not yet catered for.

**Comment by mixu** [comment] 2016-05-04 05:30
closing to clean up the issues list a bit; this looks like it may have been either old cached files but difficult to confirm.

**Closed by mixu** 2016-05-04 05:30 UTC
